// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qijvvcppszrhaaqkgygw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpanZ2Y3Bwc3pyaGFhcWtneWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjQ4NjYsImV4cCI6MjA2OTc0MDg2Nn0.DepOqxEte9pi8VgHthiJAWF27AYAn5bKg55ib-9w_Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});